// Function to generate dates between today and 7 days ago in dd-mm-YYYY format
const generateRecentDate = () => {
  const today = new Date();
  const daysAgo = Math.floor(Math.random() * 7); // Random number between 0-6 days ago
  const date = new Date(today);
  date.setDate(today.getDate() - daysAgo);

  // Format as dd-mm-YYYY
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0"); // Months are 0-based
  const year = date.getFullYear();

  return `${day}-${month}-${year}`;
};

// Function to generate creation date (older than last activity)
const generateCreationDate = () => {
  const today = new Date();
  const monthsAgo = Math.floor(Math.random() * 24) + 6; // Random between 6-30 months ago
  const date = new Date(today);
  date.setMonth(today.getMonth() - monthsAgo);

  // Format as dd-mm-YYYY
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();

  return `${day}-${month}-${year}`;
};

export const betCrawlerData = [
  {
    id: 1,
    name: "BetWinner",
    platforms: ["Instagram", "Facebook"],
    followers: 45000,
    posts: 127,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "betwinner.com",
    gateways: ["PIX", "Boleto", "Crypto"],
    cnpj: "Não identificado",
    banks: ["Nubank", "Itaú"],
    creationDate: generateCreationDate(),
  },
  {
    id: 2,
    name: "LuckyPlay",
    platforms: ["Instagram", "Twitter"],
    followers: 28000,
    posts: 89,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "luckyplay.bet",
    gateways: ["PIX", "Transferência"],
    cnpj: "12.345.678/0001-99",
    banks: ["Bradesco"],
    creationDate: generateCreationDate(),
  },
  {
    id: 3,
    name: "GoldenBet",
    platforms: ["Facebook"],
    followers: 32000,
    posts: 103,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "goldenbet.com.br",
    gateways: ["PIX", "Boleto", "Cartão"],
    cnpj: "Não identificado",
    banks: ["Santander", "Inter"],
    creationDate: generateCreationDate(),
  },
  {
    id: 4,
    name: "WinnersBet",
    platforms: ["Instagram", "Twitter"],
    followers: 18500,
    posts: 67,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "winnersbet.io",
    gateways: ["PIX", "Crypto"],
    cnpj: "23.456.789/0001-10",
    banks: ["C6", "Inter"],
    creationDate: generateCreationDate(),
  },
  {
    id: 5,
    name: "BetKing",
    platforms: ["Instagram", "Facebook", "Twitter"],
    followers: 52000,
    posts: 145,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "betking.com",
    gateways: ["PIX", "Boleto", "Transferência"],
    cnpj: "Não identificado",
    banks: ["Itaú", "Bradesco", "Nubank"],
    creationDate: generateCreationDate(),
  },
  {
    id: 6,
    name: "SambaBet",
    platforms: ["Instagram", "TikTok"],
    followers: 63000,
    posts: 215,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "sambabet.com.br",
    gateways: ["PIX", "Boleto", "Crypto"],
    cnpj: "34.567.890/0001-21",
    banks: ["Nubank", "Caixa"],
    creationDate: generateCreationDate(),
  },
  {
    id: 7,
    name: "CarnavalGames",
    platforms: ["Facebook", "YouTube"],
    followers: 41200,
    posts: 178,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "carnavalgames.bet",
    gateways: ["PIX", "Transferência"],
    cnpj: "Não identificado",
    banks: ["Banco do Brasil", "Inter"],
    creationDate: generateCreationDate(),
  },
  {
    id: 8,
    name: "CopacabanaCasino",
    platforms: ["Instagram", "Twitter", "TikTok"],
    followers: 87500,
    posts: 342,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "copacabanacasino.com",
    gateways: ["PIX", "Boleto", "Cartão", "Crypto"],
    cnpj: "45.678.901/0001-32",
    banks: ["Itaú", "Santander", "BTG"],
    creationDate: generateCreationDate(),
  },
  {
    id: 9,
    name: "IpanemaJogos",
    platforms: ["Facebook", "Instagram"],
    followers: 29800,
    posts: 112,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "ipanemajogos.bet",
    gateways: ["PIX", "Boleto"],
    cnpj: "Não identificado",
    banks: ["Nubank"],
    creationDate: generateCreationDate(),
  },
  {
    id: 10,
    name: "FuteBet Brasil",
    platforms: ["Twitter", "Instagram"],
    followers: 76300,
    posts: 289,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "futebet.com.br",
    gateways: ["PIX", "Transferência", "Crypto"],
    cnpj: "56.789.012/0001-43",
    banks: ["Bradesco", "Banco do Brasil"],
    creationDate: generateCreationDate(),
  },
  {
    id: 11,
    name: "AçaíBet",
    platforms: ["Instagram", "TikTok", "YouTube"],
    followers: 54200,
    posts: 198,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "acaibet.com.br",
    gateways: ["PIX", "Boleto"],
    cnpj: "Não identificado",
    banks: ["C6", "Inter", "Nubank"],
    creationDate: generateCreationDate(),
  },
  {
    id: 12,
    name: "CaipirinhaCasino",
    platforms: ["Facebook", "Twitter"],
    followers: 32700,
    posts: 143,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "caipirinhacasino.bet",
    gateways: ["PIX", "Crypto"],
    cnpj: "67.890.123/0001-54",
    banks: ["Itaú", "Santander"],
    creationDate: generateCreationDate(),
  },
  {
    id: 13,
    name: "GuaranáGames",
    platforms: ["Instagram"],
    followers: 21500,
    posts: 87,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "guaranagames.com",
    gateways: ["PIX"],
    cnpj: "Não identificado",
    banks: ["Nubank"],
    creationDate: generateCreationDate(),
  },
  {
    id: 14,
    name: "FeijoadadaBet",
    platforms: ["TikTok", "Instagram"],
    followers: 48900,
    posts: 231,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "feijoadadabet.bet",
    gateways: ["PIX", "Boleto", "Transferência"],
    cnpj: "78.901.234/0001-65",
    banks: ["Bradesco", "Caixa"],
    creationDate: generateCreationDate(),
  },
  {
    id: 15,
    name: "CaipiraBet",
    platforms: ["Facebook", "Instagram", "Twitter", "YouTube"],
    followers: 93200,
    posts: 376,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "caipirabet.com.br",
    gateways: ["PIX", "Boleto", "Cartão", "Crypto"],
    cnpj: "89.012.345/0001-76",
    banks: ["Itaú", "Bradesco", "Santander", "Inter"],
    creationDate: generateCreationDate(),
  },
  // Adicionando mais 20 registros tropicalizados
  {
    id: 16,
    name: "BrasilBets",
    platforms: ["Instagram", "TikTok", "Telegram"],
    followers: 124500,
    posts: 432,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "brasilbets.com",
    gateways: ["PIX", "Boleto", "Crypto", "Cartão"],
    cnpj: "Não identificado",
    banks: ["Nubank", "Inter", "PicPay"],
    creationDate: generateCreationDate(),
  },
  {
    id: 17,
    name: "JogaBina",
    platforms: ["Facebook", "Instagram"],
    followers: 38700,
    posts: 156,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "jogabina.bet",
    gateways: ["PIX", "Transferência"],
    cnpj: "90.123.456/0001-87",
    banks: ["Banco do Brasil", "Caixa"],
    creationDate: generateCreationDate(),
  },
  {
    id: 18,
    name: "TucanoBet",
    platforms: ["Instagram", "Twitter", "YouTube"],
    followers: 67800,
    posts: 289,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "tucanobet.com.br",
    gateways: ["PIX", "Boleto", "Crypto"],
    cnpj: "Não identificado",
    banks: ["Itaú", "Bradesco", "Santander"],
    creationDate: generateCreationDate(),
  },
  {
    id: 19,
    name: "PantanalGames",
    platforms: ["Facebook", "Instagram", "TikTok"],
    followers: 42300,
    posts: 178,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "pantanalgames.bet",
    gateways: ["PIX", "Boleto"],
    cnpj: "01.234.567/0001-98",
    banks: ["Nubank", "Inter"],
    creationDate: generateCreationDate(),
  },
  {
    id: 20,
    name: "AmazoniaSlots",
    platforms: ["Instagram", "Telegram", "Discord"],
    followers: 83600,
    posts: 312,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "amazoniaslots.com",
    gateways: ["PIX", "Crypto", "Cartão"],
    cnpj: "Não identificado",
    banks: ["C6", "Nubank", "PicPay"],
    creationDate: generateCreationDate(),
  },
  {
    id: 21,
    name: "CangaceiroBet",
    platforms: ["Instagram", "Facebook", "YouTube"],
    followers: 59200,
    posts: 245,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "cangaceirobet.bet",
    gateways: ["PIX", "Boleto", "Transferência"],
    cnpj: "12.345.678/0001-09",
    banks: ["Bradesco", "Banco do Brasil"],
    creationDate: generateCreationDate(),
  },
  {
    id: 22,
    name: "ChurrascoGames",
    platforms: ["Facebook", "Instagram"],
    followers: 31500,
    posts: 134,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "churrascobet.com.br",
    gateways: ["PIX", "Boleto"],
    cnpj: "Não identificado",
    banks: ["Itaú", "Santander"],
    creationDate: generateCreationDate(),
  },
  {
    id: 23,
    name: "VaiVaiCasino",
    platforms: ["Instagram", "TikTok", "Telegram"],
    followers: 78900,
    posts: 298,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "vaivaicasino.com",
    gateways: ["PIX", "Crypto", "Cartão"],
    cnpj: "23.456.789/0001-10",
    banks: ["Nubank", "C6", "Inter"],
    creationDate: generateCreationDate(),
  },

  {
    id: 24,
    name: "AbacaxiBet",
    platforms: ["Instagram", "Facebook"],
    followers: 45600,
    posts: 187,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "abacaxibet.bet",
    gateways: ["PIX", "Boleto", "Transferência"],
    cnpj: "Não identificado",
    banks: ["Bradesco", "Caixa"],
    creationDate: generateCreationDate(),
  },
  {
    id: 25,
    name: "JabuticabaCasino",
    platforms: ["Instagram", "Twitter", "YouTube"],
    followers: 92300,
    posts: 356,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "jabuticabacasino.com",
    gateways: ["PIX", "Crypto", "Cartão"],
    cnpj: "34.567.890/0001-21",
    banks: ["Itaú", "Santander", "BTG"],
    creationDate: generateCreationDate(),
  },
  {
    id: 26,
    name: "CuiaBets",
    platforms: ["Facebook", "Instagram"],
    followers: 28700,
    posts: 123,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "cuiabets.bet",
    gateways: ["PIX"],
    cnpj: "45.678.901/0001-32",
    banks: ["Nubank"],
    creationDate: generateCreationDate(),
  },
  {
    id: 27,
    name: "PãoDeQueijoGames",
    platforms: ["Instagram", "TikTok"],
    followers: 51400,
    posts: 214,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "paodequejogames.com.br",
    gateways: ["PIX", "Boleto"],
    cnpj: "Não identificado",
    banks: ["Inter", "C6"],
    creationDate: generateCreationDate(),
  },
  {
    id: 28,
    name: "BrigadeiroBet",
    platforms: ["Instagram", "Facebook", "Telegram"],
    followers: 68900,
    posts: 267,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "brigadeirobet.com",
    gateways: ["PIX", "Crypto", "Transferência"],
    cnpj: "56.789.012/0001-43",
    banks: ["Bradesco", "Itaú", "Nubank"],
    creationDate: generateCreationDate(),
  },
  {
    id: 29,
    name: "CoxinhaBets",
    platforms: ["Facebook", "Instagram", "YouTube"],
    followers: 47200,
    posts: 198,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "coxinhabets.bet",
    gateways: ["PIX", "Boleto"],
    cnpj: "67.890.123/0001-54",
    banks: ["Banco do Brasil", "Caixa"],
    creationDate: generateCreationDate(),
  },
  {
    id: 30,
    name: "PaçocaGames",
    platforms: ["Instagram", "TikTok", "Discord"],
    followers: 73500,
    posts: 287,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "pacocagames.com",
    gateways: ["PIX", "Crypto", "Cartão"],
    cnpj: "Não identificado",
    banks: ["Nubank", "Inter", "PicPay"],
    creationDate: generateCreationDate(),
  },
  {
    id: 31,
    name: "TapiocaBet",
    platforms: ["Instagram", "Facebook"],
    followers: 39800,
    posts: 165,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "tapiocabet.bet",
    gateways: ["PIX", "Boleto"],
    cnpj: "78.901.234/0001-65",
    banks: ["Bradesco", "Itaú"],
    creationDate: generateCreationDate(),
  },
  {
    id: 32,
    name: "AcarajéCasino",
    platforms: ["Instagram", "Twitter", "Telegram"],
    followers: 84600,
    posts: 324,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "acarajecasino.com.br",
    gateways: ["PIX", "Crypto", "Transferência"],
    cnpj: "Não identificado",
    banks: ["Santander", "C6", "Nubank"],
    creationDate: generateCreationDate(),
  },
  {
    id: 33,
    name: "ChurrosGames",
    platforms: ["Facebook", "Instagram"],
    followers: 29400,
    posts: 132,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "churrosgames.bet",
    gateways: ["PIX"],
    cnpj: "89.012.345/0001-76",
    banks: ["Nubank"],
    creationDate: generateCreationDate(),
  },
  {
    id: 34,
    name: "PicanhaBet",
    platforms: ["Instagram", "Facebook", "YouTube"],
    followers: 62800,
    posts: 254,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "picanhabet.com",
    gateways: ["PIX", "Boleto", "Cartão"],
    cnpj: "90.123.456/0001-87",
    banks: ["Itaú", "Bradesco", "Banco do Brasil"],
    creationDate: generateCreationDate(),
  },
  {
    id: 35,
    name: "CatuabaCasino",
    platforms: ["Instagram", "TikTok", "Telegram"],
    followers: 71200,
    posts: 278,
    lastActivity: generateRecentDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "catuabacasino.bet",
    gateways: ["PIX", "Crypto", "Transferência"],
    cnpj: "Não identificado",
    banks: ["Nubank", "Inter", "C6"],
    creationDate: generateCreationDate(),
  },
];
